### ISSUE TITLE
Yarn2 compatibility

### ISSUE THREAD

**Issue by n-rodriguez** [webdeveric/webpack-assets-manifest#122]
## The problem

With :

* Yarn2 and [zero install](https://yarnpkg.com/features/zero-installs)
* webpack 5.11

when `webpack-assets-manifest` is enabled, it fails with error :

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
(node:182479) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-3fcd8c6a0a/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/NormalModule.js:171:10)
    at WebpackAssetsManifest.handleCompilation (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-assets-manifest-virtual-a945d650af/0/cache/webpack-assets-manifest-npm-5.0.0-fe18b6af02-c93c6719e2.zip/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:729:18)
    at Hook.eval [as call] (eval at create (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:988:26)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:1024:28)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:471:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:182479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:182479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Webpack config

```js
{
  mode: 'development',
  output: {
    filename: 'js/[name]-[contenthash].js',
    chunkFilename: 'js/[name]-[contenthash].chunk.js',
    hotUpdateChunkFilename: 'js/[id]-[hash].hot-update.js',
    path: '/home/nicolas/PROJECTS/CONCERTO/concerto/public/packs',
    publicPath: '/packs/'
  },
  entry: {
    'common/application': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/common/application.coffee',
    'concerto_back_office/application': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/concerto_back_office/application.coffee',
    'concerto_back_office/devise': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/concerto_back_office/devise.coffee',
    'concerto_espagne/application': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/concerto_espagne/application.coffee',
    'concerto_france/application': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/concerto_france/application.coffee',
    'concerto_france/jalis': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/concerto_france/jalis.coffee',
    'emails/default': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/emails/default.coffee',
    'emails/newsletters/v2': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/emails/newsletters/v2.coffee',
    'emails/transactional/commercial': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/emails/transactional/commercial.coffee',
    'emails/transactional/global_with_images': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/emails/transactional/global_with_images.coffee',
    'emails/transactional/global': '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend/packs/emails/transactional/global.coffee'
  },
  resolve: {
    extensions: [ '.js', '.mjs', '.ts', '.coffee' ],
    modules: [
      '/home/nicolas/PROJECTS/CONCERTO/concerto/app/frontend',
      'node_modules'
    ],
    plugins: [ [Object] ]
  },
  plugins: [
    ProvidePlugin { definitions: [Object] },
    EnvironmentPlugin { keys: [Array], defaultValues: [Object] },
    CaseSensitivePathsPlugin {
      options: {},
      logger: [Object [console]],
      pathCache: {},
      fsOperations: 0,
      primed: false
    },
    WebpackAssetsManifest {
      hooks: [Object],
      options: [Object],
      assets: [Object: null prototype] {},
      assetNames: Map(0) {},
      currentAsset: null,
      compiler: null,
      hmrRegex: null,
      [Symbol(isMerging)]: false
    },
    MiniCssExtractPlugin {
      options: [Object],
      runtimeOptions: [Object]
    }
  ],
  resolveLoader: { modules: [ 'node_modules' ], plugins: [ [Object] ] },
  optimization: { splitChunks: false },
  module: {
    strictExportPresence: true,
    rules: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  },
  devtool: 'cheap-module-source-map'
}
```
WebpackAssetsManifest options :

```js
{
  enabled: true,
  assets: [Object: null prototype] {},
  output: 'manifest.json',
  replacer: null,
  space: 2,
  writeToDisk: true,
  fileExtRegex: /\.\w{2,4}\.(?:map|gz)$|\.\w+$/i,
  sortManifest: true,
  merge: false,
  publicPath: true,
  contextRelativeKeys: false,
  apply: null,
  customize: null,
  transform: null,
  done: null,
  entrypoints: true,
  entrypointsKey: 'entrypoints',
  entrypointsUseAssets: true,
  integrity: false,
  integrityHashes: [ 'sha256', 'sha384', 'sha512' ],
  integrityPropertyName: 'integrity'
}
```

**Comment by n-rodriguez** [comment]
@webdeveric any idea?

**Comment by webdeveric** [comment]
@n-rodriguez I've seen this error message when I `npm link` the project to another project for local testing.

That error is being thrown from [`NormalModule.getCompilationHooks()`](https://github.com/webpack/webpack/blob/88610d738ff78fa3fb7f859ee284c632bca42a24/lib/NormalModule.js#L178).
Since its checking `!(compilation instanceof Compilation)`, maybe the `Compilation` being passed is from a different webpack installation?

Can you run `yarn why webpack`?

**Comment by n-rodriguez** [comment]
> Can you run `yarn why webpack`?

Sure

yarn 1 :

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ yarn why webpack
yarn why v1.22.10
[1/4] Why do we have the module "webpack"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "webpack@5.12.2"
info Has been hoisted to "webpack"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@rails#webpacker#webpack"
info Disk size without dependencies: "5.95MB"
info Disk size with unique dependencies: "10.05MB"
info Disk size with transitive dependencies: "21.96MB"
info Number of shared dependencies: 52
Done in 0.51s.
```

yarn 2 :

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ yarn why webpack
├─ @rails/webpacker@https://github.com/rails/webpacker.git#commit=1aca8aaebd21a075d42e718d2b60dfba8e8d1b70
│  └─ webpack@npm:5.12.1 [f3bf7] (via npm:^5.11.0 [f3bf7])
│
└─ concerto@workspace:.
   └─ webpack@npm:5.12.1 [b8ff6] (via npm:^5.11.1 [b8ff6])
```

**Comment by n-rodriguez** [comment]
@webdeveric hi there! any news?

error is still here : 

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
(node:104049) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5a2290c16f/0/cache/webpack-npm-5.17.0-e594321923-2840d6291d.zip/node_modules/webpack/lib/NormalModule.js:179:10)
    at WebpackAssetsManifest.handleCompilation (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-assets-manifest-virtual-2b97b71b21/0/cache/webpack-assets-manifest-npm-5.0.1-7bdcf00ed2-d418865fe4.zip/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:726:18)
    at Hook.eval [as call] (eval at create (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-08e24a9363/0/cache/webpack-npm-5.17.0-e594321923-2840d6291d.zip/node_modules/webpack/lib/Compiler.js:993:26)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-08e24a9363/0/cache/webpack-npm-5.17.0-e594321923-2840d6291d.zip/node_modules/webpack/lib/Compiler.js:1035:29
    at Hook.eval [as callAsync] (eval at create (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-08e24a9363/0/cache/webpack-npm-5.17.0-e594321923-2840d6291d.zip/node_modules/webpack/lib/Compiler.js:1030:28)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-08e24a9363/0/cache/webpack-npm-5.17.0-e594321923-2840d6291d.zip/node_modules/webpack/lib/Compiler.js:473:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:104049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:104049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ yarn why webpack
├─ @rails/webpacker@https://github.com/rails/webpacker.git#commit=f40fa08ea6bf2cf49e1ff1417690f38b491c47be
│  └─ webpack@npm:5.17.0 [feed8] (via npm:^5.11.0 [feed8])
│
└─ concerto@workspace:.
   └─ webpack@npm:5.17.0 [b8ff6] (via npm:^5.17.0 [b8ff6])
```

**Comment by artempartos** [comment]
have the same issue

**Comment by artempartos** [comment]
as a workaround - I did next thing:
- removed plugin:
`webpackConfig.plugins.splice(2, 1)` where 2 - is an index of your WebpackAssetsManifest plugin
- then added plugin manually
```
const customConfig = {
  plugins: [
    new WebpackAssetsManifest({
      enabled: true,
      entrypoints: true,
      writeToDisk: true,
      output: 'manifest.json',
      entrypointsUseAssets: true,
      space: 2,
      publicPath: true
    }),
  ],
}

const finalConfig = merge(webpackConfig, customConfig);
```
working for me

**Comment by webdeveric** [comment]
@n-rodriguez I've created a [temp repo](https://github.com/webdeveric/wam-yarn2-demo) showing that this plugin works with Yarn 2.

I think your issue is related to multiple versions of webpack being installed (`5.11.0` and `5.17.0` in your case).

**Comment by n-rodriguez** [comment]
> (`5.11.0` and `5.17.0` in your case).

Wrong. These are requirements not the required library.

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ yarn why webpack
├─ @rails/webpacker@https://github.com/rails/webpacker.git#commit=f40fa08ea6bf2cf49e1ff1417690f38b491c47be
│  └─ webpack@npm:5.17.0 [feed8] (via npm:^5.11.0 [feed8])
│
└─ concerto@workspace:.
   └─ webpack@npm:5.17.0 [b8ff6] (via npm:^5.17.0 [b8ff6])
```

**Comment by n-rodriguez** [comment]
But thanks to @artempartos we have a workaround :+1:

**Comment by n-rodriguez** [comment]
And now the proof : 

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ ll .yarn/cache/webpack-npm-*.zip 
-rw-r--r-- 1 nicolas nicolas 960126  6 févr. 21:57 .yarn/cache/webpack-npm-5.21.1-3556a5feaa-8f2dcd43d3.zip
```

**Comment by webdeveric** [comment]
@n-rodriguez My mistake on the package versions. I read it too quickly.

But, the fact remains that I was able to use my plugin with Yarn2 without any issues.
I suspect the issue you have is related to package resolution that is specific to your project.
Can you share your repo?

**Comment by n-rodriguez** [comment]
> @n-rodriguez My mistake on the package versions. I read it too quickly.

;)

> But, the fact remains that I was able to use my plugin with Yarn2 without any issues.

I see that :+1: 

>  I suspect the issue you have is related to package resolution that is specific to your project.

Can it be related to Webpack plugins order? Because the fix is about changing plugins order.

> Can you share your repo?

Unfortunately not, it's a private repo :/

**Comment by webdeveric** [comment]
@n-rodriguez With the workaround, you're removing the plugin from the config provided by `@rails/webpacker` and adding it back in your custom config, which sounds like it resolves to the `webpack` you depend on in your `package.json`. I'm not a Rails dev and have not used `wepacker` personally so keep that in mind regarding my analysis.

---

In the `yarn why webpack` output you provided:
>nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ yarn why webpack
├─ @rails/webpacker@https://github.com/rails/webpacker.git#commit=f40fa08ea6bf2cf49e1ff1417690f38b491c47be
│  └─ webpack@npm:5.17.0 [feed8] (via npm:^5.11.0 [feed8])
│
└─ concerto@workspace:.
   └─ webpack@npm:5.17.0 [b8ff6] (via npm:^5.17.0 [b8ff6])

The hashes are  different `feed8` and `b8ff6` and they should point to strings that begin with `virtual:feed8` and `virtual:b8ff6` in `.pnp.js` from your project. Somehow, Yarn has them resolving to the same zip file in the yarn cache, but virtually, they are different. I'm not sure of the significance of that but it was worth mentioning. I've only looked at a `.pnp.js` file for a few minutes so I'm not very familiar with the exact usage of each entry so this could be nothing.
