### ISSUE TITLE
Cannot add property integrity, object is not extensible

### ISSUE THREAD

**Issue by CCCoderDE** [webdeveric/webpack-assets-manifest#192]
## The problem

When adding options to the constructor `new WebpackAssetsManifest({ integrity: true })` in my webpack config, the project won't build correctly.

I am using `webpack-assets-manifest` version `5.0.6`

## Technical details

The error is:
`An unhandled exception occurred: Cannot add property integrity, object is not extensible`
`See "C:\Users\***\AppData\Local\Temp\ng-KN1lBv\angular-errors.log" for further details.`

In the angular-errors.log the following error is shown:
```
[error] HookWebpackError: Cannot add property integrity, object is not extensible
    at makeWebpackError (C:\Users\***\***\***\***\frontend\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Users\***\***\***\***\frontend\node_modules\webpack\lib\Compilation.js:2515:12
    at eval (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:87:1)
    at fn (C:\Users\***\***\***\***\frontend\node_modules\webpack\lib\Compilation.js:452:17)
    at _next1 (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:84:1)
    at eval (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:102:1)
    at fn (C:\Users\***\***\***\***\frontend\node_modules\webpack\lib\Compilation.js:464:9)
    at _next0 (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:97:1)
    at eval (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:115:1)
-- inner error --
TypeError: Cannot add property integrity, object is not extensible
    at WebpackAssetsManifest.recordSubresourceIntegrity (C:\Users\***\***\***\***\frontend\node_modules\webpack-assets-manifest\src\WebpackAssetsManifest.js:764:45)
    at fn (C:\Users\***\***\***\***\frontend\node_modules\webpack\lib\Compilation.js:450:10)
    at _next1 (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:84:1)
    at eval (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:102:1)
    at fn (C:\Users\***\***\***\***\frontend\node_modules\webpack\lib\Compilation.js:464:9)
    at _next0 (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:97:1)
    at eval (eval at create (C:\Users\***\***\***\***\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:115:1)
```

When removing the option (`new WebpackAssetsManifest()`), everything builds correctly.

### Webpack version

`5.50.0`

### Webpack config

```
const WebpackAssetsManifest = require('webpack-assets-manifest');
const path = require('path');

module.exports = {
	output: {
		path: path.join( __dirname, 'dist/frontend' ),
		filename: '[name]-[fullhash].js',
		chunkFilename: '[id]-[chunkhash].js',
	},
	plugins: [
		new WebpackAssetsManifest({ integrity: true }),
	]
};

```

### Operating system

Windows

**Comment by CCCoderDE** [comment]
@webdeveric sorry for the late reply.

I realized, that it is working perfectly fine for the "production" configuration defined in the angular.json to build my project.
However, when using the "local" configuration, it produces the error above...
Both using the `ng build` command

I will now take a look further into the problem and the differences between the two configurations to hopefully find the error. In case there are any known problems with the configurations in the angular.json please let me know

**Comment by CCCoderDE** [comment]
Ok, so I found the cause of this problem. 🥳 
The error is casued by a value in `angular.json`. When the config-value `projects > ProjectName > architect > build > configurations > ConfigName > optimization` is set to `false`, the build fails with the error mentioned. When I change that value to `true`, the build works.

It might me worth to add this to the documentation of this project, what do you think @webdeveric?

**Comment by CCCoderDE** [comment]
Ok so by creating a second webpack-config file and then referencing this for the local configuration, I manged to get it working.

This is the important part of my angular.json-File:
```
"build": {
	"builder": "@angular-builders/custom-webpack:browser",
	"options": {
		....
		"customWebpackConfig": {
			"path": "./custom-webpack.config.ts",
			"replaceDuplicatePlugins": true
		}
	},
	"configurations": {
		"production": {
			....
		},
		"dev": {
			....
		},
		"local": {
			"customWebpackConfig": {
				"path": "./custom-webpack.config.local.ts"
			}
		}
	}
},
```
- `custom-webpack.config.ts`-File with `new WebpackAssetsManifest({integrity: true})` in `plugins`
- `custom-webpack.config.local.ts`-File with `new WebpackAssetsManifest()` in `plugins`

**Comment by bertho-zero** [comment]
I have the same problem, weback is trying to create LICENSE.txt files which have asset.info which are not expandable.

I added these lines to test:
```js
console.log('asset.info', asset.info);
console.log('Object.isExtensible(asset.info)', Object.isExtensible(asset.info));

if (!Object.isExtensible(asset.info)) {
  console.log(asset);
}
```

and the result is:

```
asset.info {}
Object.isExtensible(asset.info) false
{
  name: 'outdated.js.LICENSE.txt',
  source: RawSource {
    _value: '... useless text ...'
  },
  info: {}
}
```
just before the error.
