### ISSUE TITLE
inDevServer method crashes with webpack 5

### ISSUE THREAD

**Issue by blackrabbit99** [webdeveric/webpack-assets-manifest#208]
## The problem
Can not create assets manifest file after update to webpack@5.
webpack-assets-manifest throws an error in inDevServer
https://github.com/webdeveric/webpack-assets-manifest/blob/master/src/WebpackAssetsManifest.js#L838

Because `this.compiler.outputFileSystem` is ` [Object: null prototype] ` 

## Technical details
```
HookWebpackError: Cannot read properties of undefined (reading 'name')
        at makeWebpackError ($HOME/path/webpack.buildconfig.library/node_modules/webpack/lib/HookWebpackError.js:48:9)
        at $HOME/path/webpack.buildconfig.library/node_modules/webpack/lib/Compilation.js:3055:12
        at eval (eval at create ($HOME/path/webpack.buildconfig.library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    -- inner error --
    TypeError: Cannot read properties of undefined (reading 'name')
        at WebpackAssetsManifest.inDevServer ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:838:97)
        at WebpackAssetsManifest.getOutputPath ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:856:15)
        at WebpackAssetsManifest.emitAssetsManifest ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:418:29)
        at WebpackAssetsManifest.handleProcessAssetsReport ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:633:16)
        at fn ($HOME/path/webpack.buildconfig.library/node_modules/webpack/lib/Compilation.js:534:19)
        at _next4 (eval at create ($HOME/path/webpack.buildconfig.library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:17)
        at eval (eval at create ($HOME/path/webpack.buildconfig.library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    caused by plugins in Compilation.hooks.processAssets
    TypeError: Cannot read properties of undefined (reading 'name')
        at WebpackAssetsManifest.inDevServer ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:838:97)
        at WebpackAssetsManifest.getOutputPath ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:856:15)
        at WebpackAssetsManifest.emitAssetsManifest ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:418:29)
        at WebpackAssetsManifest.handleProcessAssetsReport ($HOME/path/webpack.buildconfig.library/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:633:16)
        at fn ($HOME/path/webpack.buildconfig.library/node_modules/webpack/lib/Compilation.js:534:19)
        at _next4 (eval at create ($HOME/path/webpack.buildconfig.library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:17)
        at eval (eval at create ($HOME/path/webpack.buildconfig.library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Webpack version
`webpack@5.65.0 `
### Webpack config

```
    {
      mode: 'production',
      devtool: 'hidden-source-map',
      resolve: {
        extensions: [
          '.ts',   '.tsx',
          '.js',   '.jsx',
          '.json', '.ts',
          '.tsx',  '.js',
          '.jsx',  '.json'
        ],
        alias: {}
      },
      module: {
        rules: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object]
        ]
      },
      plugins: [
        BundleAnalyzerPlugin {
          opts: [Object],
          server: null,
          logger: [Logger]
        },
        ScopeAmdModulePlugin { scope: 'deps.amd' },
        WebpackAssetsManifest {
          hooks: [Object],
          options: [Object],
          assets: [Object: null prototype] {},
          assetNames: Map(0) {},
          currentAsset: null,
          compiler: null,
          [Symbol(isMerging)]: false
        }
      ],
      optimization: { minimize: true, minimizer: [ [TerserPlugin] ] },
      entry: [
        'tests/fixtures/react.library.app.tsx',
        'tests/fixtures/index.html'
      ],
      output: {
        filename: 'react.library.app.js',
        path: '$HOME/path/webpack.buildconfig.library/tests/fixtures/dist/react-library/production'
      }
    }

```

### Operating system

`MacOs Catalina`

**Comment by webdeveric** [comment]
@blackrabbit99 This error is likely caused by something not setting or changing the `outputFileSystem`. I've never encountered this before. Webpack initially has `outputFileSystem` set to `null` but will set it to `fs` in the `NodeEnvironmentPlugin` or `MemoryFileSystem` in the dev middleware.

Do you have a minimal reproducible example repo for this issue? What does your build process look like? Are you calling webpack directly or using another tool that uses webpack internally?

**Comment by blackrabbit99** [comment]
I'm calling webpack from Jest. It is a set of test so i'm in process of migrating webpack configuration from @4 to @5.
Maybe it is Jest who works with fs in special manner.

**Comment by blackrabbit99** [comment]
Updated https://github.com/webdeveric/webpack-assets-manifest/pull/209

**Comment by webdeveric** [comment]
@blackrabbit99 I'm curious what your `outputFileSystem` actually is in your case.
Can you log some details about the compiler. You can do that by using the `apply` hook and console logging the `manifest.compiler`.

Example:

```js
{
  // ...
  apply(manifest) {
    const { inspect } = require('util');

    if (manifest.compiler.outputFileSystem === null) {
      console.log('compiler.outputFileSystem is null');
    } else {
      console.group('compiler.outputFileSystem');
      console.log(
        inspect(
          manifest.compiler.outputFileSystem,
          {
            colors: true,
            compact: true,
            depth: 0,
          },
        ),
      );
      console.groupEnd();

      if (manifest.compiler.outputFileSystem.constructor) {
        console.group('compiler.outputFileSystem.constructor');
        console.log(manifest.compiler.outputFileSystem.constructor.name);
        console.groupEnd();
      }
    }
  },
  // ... 
};
```

**Comment by blackrabbit99** [comment]
Here is the results of investigation. Please see the log below 
```
    console.log
        [Object: null prototype] {
        appendFile: [Function: appendFile],
        appendFileSync: [Function: appendFileSync],
        access: [Function: access],
        accessSync: [Function: accessSync],
        chown: [Function (anonymous)],
        chownSync: [Function (anonymous)],
        chmod: [Function (anonymous)],
        chmodSync: [Function (anonymous)],
        close: [Function: close],
        closeSync: [Function: closeSync],
        copyFile: [Function: copyFile],
        copyFileSync: [Function: copyFileSync],
        cp: [Function: cp],
        cpSync: [Function: cpSync],
        createReadStream: [Function: createReadStream],
        createWriteStream: [Function: createWriteStream],
        exists: [Function: exists],
        existsSync: [Function: existsSync],
        fchown: [Function (anonymous)],
        fchownSync: [Function (anonymous)],
        fchmod: [Function (anonymous)],
        fchmodSync: [Function (anonymous)],
        fdatasync: [Function: fdatasync],
        fdatasyncSync: [Function: fdatasyncSync],
        fstat: [Function (anonymous)],
        fstatSync: [Function (anonymous)],
        fsync: [Function: fsync],
        fsyncSync: [Function: fsyncSync],
        ftruncate: [Function: ftruncate],
        ftruncateSync: [Function: ftruncateSync],
        futimes: [Function: futimes],
        futimesSync: [Function: futimesSync],
        lchown: [Function (anonymous)],
        lchownSync: [Function (anonymous)],
        lchmod: [Function (anonymous)],
        lchmodSync: [Function (anonymous)],
        link: [Function: link],
        linkSync: [Function: linkSync],
        lstat: [Function (anonymous)],
        lstatSync: [Function (anonymous)],
        lutimes: [Function: lutimes],
        lutimesSync: [Function: lutimesSync],
        mkdir: [Function: mkdir],
        mkdirSync: [Function: mkdirSync],
        mkdtemp: [Function: mkdtemp],
        mkdtempSync: [Function: mkdtempSync],
        open: [Function: open],
        openSync: [Function: openSync],
        opendir: [Function: opendir],
        opendirSync: [Function: opendirSync],
        readdir: [Function: readdir],
        readdirSync: [Function: readdirSync],
        read: [Function: read],
        readSync: [Function (anonymous)],
        readv: [Function: readv],
        readvSync: [Function: readvSync],
        readFile: [Function: readFile],
        readFileSync: [Function: readFileSync],
        readlink: [Function: readlink],
        readlinkSync: [Function: readlinkSync],
        realpath: [Function],
        realpathSync: [Function],
        rename: [Function: rename],
        renameSync: [Function: renameSync],
        rm: [Function: rm],
        rmSync: [Function: rmSync],
        rmdir: [Function: rmdir],
        rmdirSync: [Function: rmdirSync],
        stat: [Function (anonymous)],
        statSync: [Function (anonymous)],
        symlink: [Function: symlink],
        symlinkSync: [Function: symlinkSync],
        truncate: [Function: truncate],
        truncateSync: [Function: truncateSync],
        unwatchFile: [Function: unwatchFile],
        unlink: [Function: unlink],
        unlinkSync: [Function: unlinkSync],
        utimes: [Function: utimes],
        utimesSync: [Function: utimesSync],
        watch: [Function: watch],
        watchFile: [Function: watchFile],
        writeFile: [Function: writeFile],
        writeFileSync: [Function: writeFileSync],
        write: [Function: write],
        writeSync: [Function: writeSync],
        writev: [Function: writev],
        writevSync: [Function: writevSync],
        Dir: [class Dir],
        Dirent: [class Dirent],
        Stats: [Function: Stats],
        ReadStream: [Getter/Setter],
        WriteStream: [Getter/Setter],
        FileReadStream: [Getter/Setter],
        FileWriteStream: [Getter/Setter],
        _toUnixTimestamp: [Function: toUnixTimestamp],
        F_OK: 0,
        R_OK: 4,
        W_OK: 2,
        X_OK: 1,
        constants: [Object: null prototype],
        promises: [Getter],
        gracefulify: [Function: patch] }

```

**Comment by webdeveric** [comment]
@blackrabbit99 What version of Node are you using? I'd like to match your environment while debugging.

The `fs` object from that package is still an `Object` so `constructor.name` still works.

```js
const fs = require('graceful-fs');
console.log(fs.constructor.name);
```

Webpack is just setting the [`outputFileSystem` to that `fs` object in the `NodeEnvironmentPlugin`](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/node/NodeEnvironmentPlugin.js#L46).

**Comment by blackrabbit99** [comment]
> @blackrabbit99 What version of Node are you using? I'd like to match your environment while debugging.
I'm using `node@v16.13.2`

**Comment by blackrabbit99** [comment]
Have the same results on my local. The log I sent you was made from my build's node modules

**Comment by webdeveric** [comment]
I checked with a few different versions of Node and the `fs` that webpack uses by default (in `NodeEnvironmentPlugin`) has always been an `Object`. I'm not sure where the null prototype `fs` is being created. I'm assuming it has something to do with Jest.

Can you create a minimal reproducible example that I can run locally?

**Comment by blackrabbit99** [comment]
I have the same feeling. I'm trying to localise problem because project is quite big. Working on it.

**Comment by blackrabbit99** [comment]
Try the following code

```
var fs = require('graceful-fs');

test('fake test', () => {
  console.log(fs);
  expect(1).toBe(1);
});
```

`fs` is 
```
[Object: null prototype] {
...
}
```

**Comment by webdeveric** [comment]
I was able to see the `null prototype` logs when using Jest. I don't have time to dig into it more but my assumption is that there is some auto mocking going on. I ran the same test case in Mocha and it did not give me the `null prototype` which just indicates this issue is related to Jest. I'll try to find some time later today or tomorrow to review you PR again.

**Comment by blackrabbit99** [comment]
@webdeveric could you pls publish new version to npm ?

**Comment by webdeveric** [comment]
@blackrabbit99 A new version has been published.
