### ISSUE TITLE
Webpack Assets Manifest broken with schema-utils 3.x

### ISSUE THREAD

**Issue by n-rodriguez** [webdeveric/webpack-assets-manifest#96]
- Operating System: **ArchLinux**
- Node Version: **14.13.0**
- NPM Version: **6.14.8**
- webpack Version: **4.44.2**
- webpack-assets-manifest Version: **3.1.1**

### Actual Behavior

When I run Webpack it throws an error :

```sh
nicolas@laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

TypeError: validateOptions is not a function
    at /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:63:7
    at SyncHook.eval [as call] (eval at create (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/tapable/lib/Hook.js:154:20)
    at WebpackAssetsManifest.apply (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:117:29)
    at webpack (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack/lib/webpack.js:51:13)
    at processOptions (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:272:16)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/yargs/build/lib/yargs.js:587:13)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

### How Do We Reproduce?

Run CI with `schema-utils` 3.x ?

**Comment by webdeveric** [comment]
@n-rodriguez I have an update locally. I'll try to publish to npm this week.
